# Generated by Django 5.2.8 on 2026-01-05 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Назва проєкту')),
                ('description', models.TextField(verbose_name='Опис')),
                ('image', models.ImageField(upload_to='projects/', verbose_name='Зображення')),
                ('link', models.URLField(blank=True, verbose_name='Посилання на сайт/GitHub')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Проєкт',
                'verbose_name_plural': 'Проєкти',
            },
        ),
    ]
